### ISSUE TITLE
APIKEY issue

### ISSUE THREAD

**Issue by silent-303** [jakob223/inkyphat_weather_agenda#1]
Hi there,

i am trying to get this to run, but it doesent work:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/thonny/workbench.py", line 1534, in event_generate
    handler(event)
  File "/usr/lib/python3/dist-packages/thonny/plugins/variables.py", line 57, in _handle_toplevel_response
    self.show_globals(event["globals"], "__main__")
  File "/usr/lib/python3/dist-packages/thonny/plugins/variables.py", line 64, in show_globals
    self.update_variables(globals_)
  File "/usr/lib/python3/dist-packages/thonny/memory.py", line 113, in update_variables
    self.tree.set(node_id, "value", description)
  File "/usr/lib/python3.7/tkinter/ttk.py", line 1482, in set
    res = self.tk.call(self._w, "set", item, column, value)
_tkinter.TclError: character U+1f60a is above the range (U+0000-U+FFFF) allowed by Tcl

And:

Python 3.7.3 (/usr/bin/python3)
>>> %cd /home/pi/zero/agendastats
>>> %Run phat_weather.py
Initializing PIL...
Initializing matplotlib...
Other init...
Getting data from google calendar...
Weather forecast...
Traceback (most recent call last):
  File "/home/pi/zero/agendastats/phat_weather.py", line 37, in <module>
    with forecast(APIKEY, *LOCATION, units=UNITS) as location:
  File "/home/pi/.local/lib/python3.7/site-packages/darksky/__init__.py", line 7, in forecast
    return Forecast(key, latitude, longitude, time, timeout, **queries)
  File "/home/pi/.local/lib/python3.7/site-packages/darksky/forecast.py", line 17, in __init__
    self.refresh(timeout, **queries)
  File "/home/pi/.local/lib/python3.7/site-packages/darksky/forecast.py", line 54, in refresh
    raise requests.exceptions.HTTPError('Bad response')
requests.exceptions.HTTPError: Bad response
>>> 

In am very new to this and would be happy for help.
Thanks alot

**Comment by aaazalea** [comment]
Hmm, I'll try to look at my setup in the next day or two and see what might be wrong.
